"""Shell completion: generated from the parser, so every command and option is in every script, and the bash script is
run in a real bash (and the zsh one parsed by a real zsh) wherever they are installed."""

import argparse
import re
import shutil
import subprocess
from pathlib import Path

import pytest

from unifi_sentinel import cli
from unifi_sentinel.completion import (
    PROGRAM,
    SHELLS,
    VALUE_HINTS,
    bash_script,
    fish_script,
    script,
    spec,
    zsh_script,
)
from unifi_sentinel.diagnose import AREA_NAMES

BASH, ZSH, FISH = shutil.which("bash"), shutil.which("zsh"), shutil.which("fish")


def parser():
    return cli.build_parser()


def every_option():
    s = spec(parser())
    return [(None, o) for o in s.options] + [(c.name, o) for c in s.commands for o in c.options]


def run(argv, capsys):
    code = cli.main(argv)
    captured = capsys.readouterr()
    return code, captured.out, captured.err


# -- what the scripts must contain ------------------------------------------------------------------------------

@pytest.mark.parametrize("shell", SHELLS)
def test_every_command_and_every_option_is_in_the_script(shell):
    text = script(shell, parser())
    s = spec(parser())
    for command in s.commands:
        assert re.search(rf"(?<![\w-]){re.escape(command.name)}(?![\w])", text), command.name
    for _scope, option in every_option():
        for flag in option.flags:
            if shell == "fish":
                needle = f"-l {flag[2:]}" if flag.startswith("--") else f"-s {flag[1:]}"
            else:
                needle = flag
            assert needle in text, f"{flag} is missing from the {shell} script"


@pytest.mark.parametrize("shell", SHELLS)
def test_a_script_is_plain_text_that_is_the_same_every_time(shell):
    first, second = script(shell, parser()), script(shell, parser())
    assert first == second and first.endswith("\n") and not first.endswith("\n\n")
    assert not re.search(r"[\t\r\x00-\x08\x0b\x0c\x0e-\x1f\x7f]", first), "control characters in the script"
    assert PROGRAM in first and "generated by" in first


def test_the_spec_reads_choices_paths_and_flags_from_the_parser():
    s = spec(parser())
    diagnose = next(c for c in s.commands if c.name == "diagnose")
    options = {o.long: o for o in diagnose.options}
    assert options["--fail-on"].choices == ("info", "warning", "critical") and options["--fail-on"].takes_value
    assert options["--config"].path and options["--json"].takes_value is False
    assert options["--only"].comma_list and options["--only"].choices == tuple(AREA_NAMES)
    assert next(c for c in s.commands if c.name == "query").choices == ("all", "devices", "clients", "reservations", "ports")
    assert next(c for c in s.commands if c.name == "diff").files
    assert next(c for c in s.commands if c.name == "completion").choices == SHELLS
    assert all(c.help for c in s.commands)


def test_the_value_hints_name_options_that_exist_and_the_areas_are_the_real_ones():
    long_flags = {o.long for _, o in every_option()}
    assert set(VALUE_HINTS) <= long_flags
    assert VALUE_HINTS["--only"] == VALUE_HINTS["--skip"] == tuple(AREA_NAMES)
    assert VALUE_HINTS["--band"] == ("2.4", "5", "6")


# -- bash, run for real --------------------------------------------------------------------------------------------

@pytest.fixture
def complete(tmp_path):
    if not BASH:
        pytest.skip("bash is not installed")
    path = tmp_path / "completion.bash"
    path.write_text(bash_script(parser()))

    def reply(words, index, cwd=None):
        quoted = " ".join(f"'{w}'" for w in words)
        done = subprocess.run(
            [BASH, "--noprofile", "--norc", "-c",
             f"source '{path}'; COMP_WORDS=({quoted}); COMP_CWORD={index}; _unifi_sentinel; "
             'printf "%s\\n" "${COMPREPLY[@]}"'], capture_output=True, text=True, check=True, cwd=cwd)
        return done.stdout.split()

    return reply


def test_bash_completes_commands(complete):
    assert complete([PROGRAM, "di"], 1) == ["diff", "diagnose"]
    assert complete([PROGRAM, "comp"], 1) == ["completion"]
    assert "diagnose" in complete([PROGRAM, ""], 1) and "query" in complete([PROGRAM, ""], 1)


def test_bash_completes_options_of_the_command_and_the_global_ones(complete):
    assert complete([PROGRAM, "diagnose", "--fa"], 2) == ["--fail-on"]
    assert "--notify-dry-run" in complete([PROGRAM, "diagnose", "--notify"], 2)
    assert complete([PROGRAM, "--tim"], 1) == ["--timeout"]
    assert {"--help", "--version", "--verbose", "--env-file"} <= set(complete([PROGRAM, "--"], 1))
    assert "--only" not in complete([PROGRAM, "wifi", "--"], 2)             # another command's option


def test_bash_completes_the_values_of_options_and_positionals(complete):
    assert complete([PROGRAM, "diagnose", "--fail-on", ""], 3) == ["info", "warning", "critical"]
    assert complete([PROGRAM, "audit", "--fail-on", ""], 3) == ["info", "warning"]
    assert complete([PROGRAM, "events", "--severity", "h"], 3) == ["high"]
    assert complete([PROGRAM, "wifi", "--band", ""], 3) == ["2.4", "5", "6"]
    assert complete([PROGRAM, "query", ""], 2) == ["all", "devices", "clients", "reservations", "ports"]
    assert complete([PROGRAM, "completion", ""], 2) == ["bash", "zsh", "fish"]


def test_bash_completes_one_area_at_a_time_in_a_comma_list(complete):
    assert complete([PROGRAM, "diagnose", "--only", "po"], 3) == ["ports"]
    assert complete([PROGRAM, "diagnose", "--only", "ports,w"], 3) == ["ports,wan", "ports,wifi"]
    assert complete([PROGRAM, "diagnose", "--skip", "events,"], 3)[:2] == ["events,devices", "events,health"]


def test_bash_skips_the_value_of_a_global_option_to_find_the_command(complete):
    assert complete([PROGRAM, "--timeout", "5", "diag"], 3) == ["diagnose"]
    assert complete([PROGRAM, "--env-file", "x.env", "diagnose", "--fa"], 4) == ["--fail-on"]


def test_bash_completes_file_names_for_path_options(complete, tmp_path):
    (tmp_path / "lab.env").write_text("")
    (tmp_path / "other.txt").write_text("")
    assert complete([PROGRAM, "--env-file", "la"], 2, cwd=tmp_path) == ["lab.env"]
    assert complete([PROGRAM, "diagnose", "--config", "ot"], 3, cwd=tmp_path) == ["other.txt"]
    assert complete([PROGRAM, "export", "-o", "la"], 3, cwd=tmp_path) == ["lab.env"]


def test_bash_offers_nothing_where_a_value_is_free_text(complete):
    assert complete([PROGRAM, "query", "--search", "pr"], 3) == []
    assert complete([PROGRAM, "diagnose", "positional-that-does-not-exist"], 2) == []


def test_the_bash_script_registers_itself_with_the_default_fallback():
    text = bash_script(parser())
    assert text.rstrip().endswith(f"complete -o default -F _unifi_sentinel {PROGRAM}")
    assert "${!" not in text and "declare -A" not in text and "compopt" not in text       # bash 3.2 has none of these


@pytest.mark.skipif(not BASH, reason="bash is not installed")
def test_the_bash_script_has_valid_syntax(tmp_path):
    path = tmp_path / "c.bash"
    path.write_text(bash_script(parser()))
    assert subprocess.run([BASH, "-n", str(path)], capture_output=True, text=True).returncode == 0


# -- zsh and fish ---------------------------------------------------------------------------------------------------

@pytest.mark.skipif(not ZSH, reason="zsh is not installed")
def test_the_zsh_script_has_valid_syntax_and_registers_itself(tmp_path):
    path = tmp_path / "_unifi-sentinel"
    path.write_text(zsh_script(parser()))
    assert subprocess.run([ZSH, "-n", str(path)], capture_output=True, text=True).returncode == 0
    done = subprocess.run([ZSH, "-f", "-c", f"compdef() {{ echo \"registered $*\" }}; source '{path}'"],
                          capture_output=True, text=True)
    assert done.stdout.strip() == f"registered _unifi_sentinel {PROGRAM}" and done.returncode == 0


def test_the_zsh_script_describes_commands_and_options_natively():
    text = zsh_script(parser())
    assert text.startswith(f"#compdef {PROGRAM}\n") and "_arguments -C" in text and "_describe -t commands" in text
    assert "'--fail-on[" in text and ":(info warning critical)" in text and ":_files" in text
    assert "_values -s , " in text                                    # the comma lists


@pytest.mark.skipif(not FISH, reason="fish is not installed")
def test_the_fish_script_has_valid_syntax(tmp_path):
    path = tmp_path / "c.fish"
    path.write_text(fish_script(parser()))
    assert subprocess.run([FISH, "-n", str(path)], capture_output=True, text=True).returncode == 0


def test_the_fish_script_is_one_complete_command_per_line_with_balanced_quotes():
    lines = fish_script(parser()).splitlines()
    commands = [line for line in lines if not line.startswith("#")]
    assert commands[0] == f"complete -c {PROGRAM} -f"
    for line in commands:
        assert line.startswith(f"complete -c {PROGRAM}"), line
        assert len(re.findall(r"(?<!\\)'", line)) % 2 == 0, line
    assert any("-l fail-on -x -a 'info warning critical'" in line for line in commands)
    assert any("-l env-file -r -F" in line for line in commands)
    assert any("__fish_seen_subcommand_from diff" in line and line.endswith("-F") for line in commands)


# -- awkward help text ------------------------------------------------------------------------------------------------

def tricky_parser():
    top = argparse.ArgumentParser(prog=PROGRAM)
    top.add_argument("--note", help="it's [bold]: 100%% sure, 'quoted' and \\back\\slashed, with $HOME and `ticks`")
    sub = top.add_subparsers(dest="command")
    child = sub.add_parser("act", help="do it: [now], 'please'")
    child.add_argument("-x", "--ex", metavar="A:B", help="a\nmultiline\n   help [text]")
    return top


def test_awkward_help_text_cannot_break_a_script():
    top = tricky_parser()
    s = spec(top)
    note = next(o for o in s.options if o.long == "--note")
    assert note.help == "it's [bold]: 100% sure, 'quoted' and \\back\\slashed, with $HOME and `ticks`"
    ex = next(o for o in s.commands[0].options if o.long == "--ex")
    assert ex.help == "a multiline help [text]" and ex.flags == ("-x", "--ex")
    for shell in ("bash", "zsh", "fish"):
        script(shell, top)                                           # does not raise
    fish = fish_script(top)
    assert "-d 'it\\'s [bold]: 100% sure, \\'quoted\\' and \\\\back\\\\slashed, with $HOME and `ticks`'" in fish


@pytest.mark.skipif(not ZSH, reason="zsh is not installed")
def test_awkward_help_text_still_gives_zsh_a_valid_script(tmp_path):
    path = tmp_path / "_tricky"
    path.write_text(zsh_script(tricky_parser()))
    done = subprocess.run([ZSH, "-n", str(path)], capture_output=True, text=True)
    assert done.returncode == 0, done.stderr


@pytest.mark.skipif(not BASH, reason="bash is not installed")
def test_awkward_help_text_still_gives_bash_a_valid_script(tmp_path):
    path = tmp_path / "tricky.bash"
    path.write_text(bash_script(tricky_parser()))
    assert subprocess.run([BASH, "-n", str(path)], capture_output=True, text=True).returncode == 0


# -- the command ----------------------------------------------------------------------------------------------------

@pytest.mark.parametrize("shell", SHELLS)
def test_the_command_prints_the_script_without_a_configuration_or_a_controller(monkeypatch, capsys, shell):
    def forbidden(*args, **kwargs):
        raise AssertionError("the completion command must not build a client")

    monkeypatch.setattr(cli.UniFiClient, "from_config", classmethod(forbidden))
    code, out, err = run(["completion", shell], capsys)       # no .env, no CONTROLLER_URL: the test environment is empty
    assert code == 0 and err == "" and out.rstrip("\n") == script(shell, parser()).rstrip("\n")


def test_a_missing_or_unknown_shell_is_a_usage_error(capsys):
    for argv in (["completion"], ["completion", "powershell"]):
        with pytest.raises(SystemExit) as stop:
            cli.main(argv)
        assert stop.value.code == cli.EXIT_USAGE
    assert "invalid choice: 'powershell' (choose from 'bash', 'zsh', 'fish')" in capsys.readouterr().err


def test_the_command_runs_from_the_launcher(tmp_path):
    import sys

    root = Path(__file__).resolve().parent.parent
    done = subprocess.run([sys.executable, str(root / "unifi-sentinel.py"), "completion", "zsh"], capture_output=True,
                          text=True, cwd=tmp_path)
    assert done.returncode == 0 and done.stdout.startswith("#compdef unifi-sentinel") and done.stderr == ""


def test_awkward_help_text_is_escaped_the_way_zsh_arguments_reads_it():
    """`zsh -n` cannot see these: an unescaped colon splits an _arguments field, a bare bracket ends the description
    and a single backslash is eaten, so the exact text is pinned."""
    lines = zsh_script(tricky_parser()).splitlines()
    note = next(line for line in lines if "'--note[" in line)
    assert note.endswith(" \\")                                       # a continuation line of the _arguments call
    assert note[:-2] == (r"        '--note[it'\''s \[bold\]\: 100% sure, '\''quoted'\'' and \\back\\slashed, "
                         r"with $HOME and `ticks`]:note: '")
    assert r"                'act:do it\: \[now\], '\''please'\'''" in lines
    assert r"                        '(-x --ex)'{-x,--ex}'[a multiline help \[text\]]:A\:B: ' && ret=0" in lines
