"""Shell completion for bash, zsh and fish, generated from the argument parser.

The scripts are not written by hand: ``spec`` reads every option, choice, path-typed option and help text from the
real ``argparse`` parser, so a new command or option is completed the day it exists (``tests/test_completion.py``
checks that every one appears in every script, and runs the bash script in a real bash). Nothing here contacts the
controller or reads the configuration; ``hlp completion SHELL`` just prints the script.

Values argparse cannot express are listed in ``VALUE_HINTS``. Options whose metavar contains a comma
(``AREA[,AREA...]``) complete one item at a time.
"""

import argparse
from dataclasses import dataclass
from pathlib import Path
from typing import Dict, List, Tuple

from .diagnose import AREA_NAMES

PROGRAM = "hlp"
SHELLS = ("bash", "zsh", "fish")
VALUE_HINTS: Dict[str, Tuple[str, ...]] = {
    "--only": tuple(AREA_NAMES), "--skip": tuple(AREA_NAMES), "--band": ("2.4", "5", "6"),
}


@dataclass(frozen=True)
class Option:
    flags: Tuple[str, ...]
    help: str
    takes_value: bool
    choices: Tuple[str, ...] = ()
    path: bool = False
    metavar: str = ""
    repeatable: bool = False

    @property
    def long(self) -> str:
        return next((f for f in self.flags if f.startswith("--")), self.flags[0])

    @property
    def comma_list(self) -> bool:
        return "," in self.metavar


@dataclass(frozen=True)
class Command:
    name: str
    help: str
    options: Tuple[Option, ...]
    choices: Tuple[str, ...] = ()          # the values of a positional argument that has a fixed set
    files: bool = False                    # a positional that is a file (``diff``)


@dataclass(frozen=True)
class Spec:
    options: Tuple[Option, ...]
    commands: Tuple[Command, ...]


def _help(text: object) -> str:
    """One line: argparse help may span lines and escapes a literal percent as ``%%``."""
    return " ".join(str(text or "").replace("%%", "%").split())


def _options(parser: argparse.ArgumentParser) -> Tuple[Option, ...]:
    found = []
    for action in parser._actions:
        if not action.option_strings:
            continue
        choices = tuple(str(c) for c in (action.choices or ())) or VALUE_HINTS.get(
            next((f for f in action.option_strings if f.startswith("--")), ""), ())
        found.append(Option(tuple(action.option_strings), _help(action.help), action.nargs != 0, choices,
                            action.type is Path, str(action.metavar or ""),
                            isinstance(action, argparse._AppendAction)))
    return tuple(found)


def spec(parser: argparse.ArgumentParser) -> Spec:
    """Everything the scripts need, read from ``parser``."""
    subparsers = next(a for a in parser._actions if isinstance(a, argparse._SubParsersAction))
    helps = {pseudo.dest: _help(pseudo.help) for pseudo in subparsers._choices_actions}
    commands = []
    for name, sub in subparsers.choices.items():
        positionals = [a for a in sub._actions if not a.option_strings]
        commands.append(Command(
            name, helps.get(name, ""), _options(sub),
            choices=next((tuple(str(c) for c in a.choices) for a in positionals if a.choices), ()),
            files=any(a.dest == "refs" or a.type is Path for a in positionals)))
    return Spec(_options(parser), tuple(commands))


def _words(items) -> str:
    return " ".join(items)


# -- bash ------------------------------------------------------------------------------------------------------

def _bash_value_branch(option: Option) -> List[str]:
    if option.path:
        return ['COMPREPLY=( $(compgen -f -- "$cur") )']
    if option.choices and option.comma_list:
        words = _words(option.choices)
        return ['case "$cur" in',
                f'    *,*) COMPREPLY=( $(compgen -P "${{cur%,*}}," -W "{words}" -- "${{cur##*,}}") ) ;;',
                f'    *) COMPREPLY=( $(compgen -W "{words}" -- "$cur") ) ;;', "esac"]
    if option.choices:
        return [f'COMPREPLY=( $(compgen -W "{_words(option.choices)}" -- "$cur") )']
    return []                                                    # free text: the shell's default completion


_BASH = """\
# bash completion for @PROGRAM@, generated by `@PROGRAM@ completion bash`.
# Use it with: source <(@PROGRAM@ completion bash)
_hlp() {
    local cur prev cmd i cmd_index positional_seen skip word j
    COMPREPLY=()
    cur="${COMP_WORDS[COMP_CWORD]}"
    prev="${COMP_WORDS[COMP_CWORD-1]}"
    cmd=""
    cmd_index=0
    i=1
    while [ "$i" -lt "$COMP_CWORD" ]; do
        case "${COMP_WORDS[$i]}" in
@SKIP_VALUES@
            -*) ;;
            *) cmd="${COMP_WORDS[$i]}"; cmd_index=$i; break ;;
        esac
        i=$((i + 1))
    done

    case "$cmd:$prev" in
@VALUES@
    esac

    if [ -z "$cmd" ]; then
        case "$cur" in
            -*) COMPREPLY=( $(compgen -W "@GLOBAL_OPTIONS@" -- "$cur") ) ;;
            *) COMPREPLY=( $(compgen -W "@COMMANDS@" -- "$cur") ) ;;
        esac
        return 0
    fi

    case "$cur" in
        -*)
            case "$cmd" in
@COMMAND_OPTIONS@
            esac ;;
        *)
            case "$cmd" in
@POSITIONALS@
            esac ;;
    esac
    return 0
}
complete -o default -F _hlp @PROGRAM@
"""


def bash_script(parser: argparse.ArgumentParser) -> str:
    """A bash completion function (it works in bash 3.2 as well as 5: no associative arrays, no ``compopt``)."""
    s = spec(parser)
    values = []
    for scope, options in [("", s.options), *[(c.name, c.options) for c in s.commands]]:
        for option in options:
            if option.takes_value:
                patterns = "|".join(f"{scope}:{flag}" for flag in option.flags)
                body = _bash_value_branch(option) + ["return 0 ;;"]
                values += [f"        {patterns})"] + [f"            {line}" for line in body]
    taking = "|".join(f for o in s.options if o.takes_value for f in o.flags)
    # a global option that takes a value: skip it and its value when looking for the command (no such option, no branch)
    skip_values = f"            {taking}) i=$((i + 1)) ;;\n" if taking else ""
    command_options = [
        f'                {c.name}) COMPREPLY=( $(compgen -W "{_words(f for o in c.options for f in o.flags)}"'
        ' -- "$cur") ) ;;' for c in s.commands]
    positionals = []
    for c in s.commands:
        if not c.choices:
            continue
        taking = "|".join(f for o in c.options if o.takes_value for f in o.flags)
        scan = ["                    positional_seen=0", "                    skip=0",
                "                    j=$((cmd_index + 1))",
                '                    while [ "$j" -lt "$COMP_CWORD" ]; do',
                '                        word="${COMP_WORDS[$j]}"',
                '                        if [ "$skip" -eq 1 ]; then',
                "                            skip=0",
                "                        else"]
        if taking:
            scan += [f'                            case "$word" in {taking}) skip=1 ;;',
                     '                                -*) ;;',
                     '                                *) positional_seen=1 ;;',
                     "                            esac"]
        else:
            scan += ['                            case "$word" in -*) ;;',
                     "                                *) positional_seen=1 ;;",
                     "                            esac"]
        scan += ["                        fi", "                        j=$((j + 1))",
                 "                    done",
                 '                    if [ "$positional_seen" -eq 0 ]; then',
                 f'                        COMPREPLY=( $(compgen -W "{_words(c.choices)}" -- "$cur") )',
                 "                    fi ;;"]
        positionals.append(f"                {c.name})\n" + "\n".join(scan))
    return (_BASH.replace("@PROGRAM@", PROGRAM)
            .replace("@SKIP_VALUES@\n", skip_values)
            .replace("@VALUES@", "\n".join(values))
            .replace("@GLOBAL_OPTIONS@", _words(f for o in s.options for f in o.flags))
            .replace("@COMMANDS@", _words(c.name for c in s.commands))
            .replace("@COMMAND_OPTIONS@", "\n".join(command_options))
            .replace("@POSITIONALS@", "\n".join(positionals)))


# -- zsh -------------------------------------------------------------------------------------------------------

def _zsh_text(text: str) -> str:
    """Text inside a single-quoted ``_arguments`` or ``_describe`` entry."""
    return (text.replace("\\", "\\\\").replace("[", "\\[").replace("]", "\\]").replace(":", "\\:")
            .replace("'", "'\\''"))


def _zsh_action(option: Option) -> str:
    if option.path:
        return f"{_zsh_text(option.metavar or 'file')}:_files"
    label = _zsh_text(option.metavar or option.long.lstrip("-"))
    if option.choices and option.comma_list:
        return f"{label}:_values -s , {label.replace(' ', '_') or 'value'} {_words(option.choices)}"
    if option.choices:
        return f"{label}:({_words(option.choices)})"
    return f"{label}: "


def _zsh_spec(option: Option) -> str:
    description = _zsh_text(option.help)
    action = f":{_zsh_action(option)}" if option.takes_value else ""
    if len(option.flags) == 1:
        return f"'{option.flags[0]}[{description}]{action}'"
    exclusive = f"({' '.join(option.flags)})"
    return f"'{exclusive}'{{{','.join(option.flags)}}}'[{description}]{action}'"


_ZSH = """\
#compdef @PROGRAM@

# zsh completion for @PROGRAM@, generated by `@PROGRAM@ completion zsh`.
# Use it with: @PROGRAM@ completion zsh > "${fpath[1]}/_@PROGRAM@"  (then restart the shell)
_hlp() {
    local curcontext="$curcontext" state state_descr line ret=1
    typeset -A opt_args
    _arguments -C \\
@GLOBAL@
        '1: :->command' \\
        '*:: :->args' && ret=0

    case $state in
        command)
            local -a commands
            commands=(
@COMMANDS@
            )
            _describe -t commands '@PROGRAM@ command' commands && ret=0
            ;;
        args)
            case $line[1] in
@PER_COMMAND@
            esac
            ;;
    esac
    return ret
}

if [ "$funcstack[1]" = "_hlp" ]; then
    _hlp "$@"
else
    compdef _hlp @PROGRAM@
fi
"""


def zsh_script(parser: argparse.ArgumentParser) -> str:
    """A native zsh completion function (``_arguments`` and ``_describe``)."""
    s = spec(parser)
    per_command = []
    for c in s.commands:
        specs = [_zsh_spec(o) for o in c.options]
        if c.choices:
            specs.append(f"'1:{_zsh_text(c.name)}:({_words(c.choices)})'")
        if c.files:
            specs.append("'*:snapshot:_files'")
        block = [f"                {c.name})"]
        if specs:
            block.append("                    _arguments \\")
            block += [f"                        {item} \\" for item in specs[:-1]]
            block.append(f"                        {specs[-1]} && ret=0")
        block.append("                    ;;")
        per_command += block
    return (_ZSH.replace("@PROGRAM@", PROGRAM)
            .replace("@GLOBAL@", "\n".join(f"        {_zsh_spec(o)} \\" for o in s.options))
            .replace("@COMMANDS@", "\n".join(f"                '{_zsh_text(c.name)}:{_zsh_text(c.help)}'"
                                             for c in s.commands))
            .replace("@PER_COMMAND@", "\n".join(per_command)))


# -- fish ------------------------------------------------------------------------------------------------------

def _fish_text(text: str) -> str:
    return "'" + text.replace("\\", "\\\\").replace("'", "\\'") + "'"


def _fish_option(option: Option, condition: str) -> str:
    parts = [f"complete -c {PROGRAM}", f"-n {_fish_text(condition)}"]
    for flag in option.flags:
        parts.append(f"-l {flag[2:]}" if flag.startswith("--") else f"-s {flag[1:]}")
    if option.takes_value:
        parts.append("-r -F" if option.path else "-x")
        if option.choices and not option.comma_list:
            parts.append(f"-a {_fish_text(_words(option.choices))}")
        elif option.choices:
            parts.append(f"-a {_fish_text(f'(__hlp_comma_values {_words(option.choices)})')}")
    parts.append(f"-d {_fish_text(option.help)}")
    return " ".join(parts)


def fish_script(parser: argparse.ArgumentParser) -> str:
    """fish ``complete`` commands."""
    s = spec(parser)
    out = [f"# fish completion for {PROGRAM}, generated by `{PROGRAM} completion fish`.",
           f"# Use it with: {PROGRAM} completion fish > ~/.config/fish/completions/{PROGRAM}.fish",
           f"complete -c {PROGRAM} -f"]
    if any(o.comma_list for c in s.commands for o in c.options):
        out += [
            "function __hlp_comma_values",
            "    set -l current (commandline -ct)",
            "    set -l prefix ''",
            "    if string match -q '*,*' -- \"$current\"",
            "        set prefix (string replace -r ',[^,]*$' ',' -- \"$current\")",
            "    end",
            "    set -l used (string split ',' -- \"$current\")",
            "    for value in $argv",
            "        if not contains -- \"$value\" $used",
            "            echo \"$prefix$value\"",
            "        end",
            "    end",
            "end",
        ]
    if any(c.choices for c in s.commands):
        global_taking = [flag for o in s.options if o.takes_value for flag in o.flags]
        out += [
            "function __hlp_positional_available --argument-names command",
            "    set -l found_command false",
            "    set -l skip false",
            "    for word in (commandline -opc)",
            "        if not $found_command",
            "            if $skip",
            "                set skip false",
            "                continue",
            "            end",
        ]
        if global_taking:
            out += [
                "            switch $word",
                *[f"                case {_fish_text(flag)}" for flag in global_taking],
                "                    set skip true",
                "                    continue",
                "            end",
            ]
        out += [
            "            if test \"$word\" = \"$command\"",
            "                set found_command true",
            "            end",
            "            continue",
            "        end",
            "        if $skip",
            "            set skip false",
            "            continue",
            "        end",
            "        switch \"$command:$word\"",
        ]
        for c in s.commands:
            taking = [f"{c.name}:{flag}" for o in c.options if o.takes_value for flag in o.flags]
            if taking:
                out += [f"            case {' '.join(_fish_text(flag) for flag in taking)}",
                        "                set skip true",
                        "                continue"]
        out += [
            "        end",
            "        switch $word",
            "            case '-*'",
            "                continue",
            "            case '*'",
            "                return 1",
            "        end",
            "    end",
            "    return 0",
            "end",
        ]
    out += [_fish_option(o, "__fish_use_subcommand") for o in s.options]
    for c in s.commands:
        out.append(f"complete -c {PROGRAM} -n '__fish_use_subcommand' -a {_fish_text(c.name)} -d {_fish_text(c.help)}")
    for c in s.commands:
        condition = f"__fish_seen_subcommand_from {c.name}"
        out += [_fish_option(o, condition) for o in c.options]
        if c.choices:
            position_condition = f"{condition}; and __hlp_positional_available {c.name}"
            out.append(f"complete -c {PROGRAM} -n {_fish_text(position_condition)} -a {_fish_text(_words(c.choices))}")
        if c.files:
            out.append(f"complete -c {PROGRAM} -n {_fish_text(condition)} -F")
    return "\n".join(out) + "\n"


def script(shell: str, parser: argparse.ArgumentParser) -> str:
    """The completion script for ``shell`` (one of ``SHELLS``)."""
    return {"bash": bash_script, "zsh": zsh_script, "fish": fish_script}[shell](parser)


__all__ = ["PROGRAM", "SHELLS", "VALUE_HINTS", "bash_script", "fish_script", "script", "spec", "zsh_script"]
