// Generates src/generated/*.ts from report (docs/schemas) and terminal API (docs/terminal) JSON Schemas.
//
// The output is committed and checked in CI: `npm run check:types` regenerates it and fails on any difference, so a
// schema change that was not followed by `npm run generate:types` cannot be merged. Nothing here depends on the clock
// or the machine: files are processed in sorted order and the banner has no date.
import { mkdir, readdir, readFile, rm, writeFile } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";

import { compile } from "json-schema-to-typescript";

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const schemaDir = path.resolve(root, "..", "docs", "schemas");
const terminalSchemaDir = path.resolve(root, "..", "docs", "terminal");
const outDir = path.resolve(root, "src", "generated");

const banner =
  "/* eslint-disable */\n" +
  "/**\n" +
  " * Generated by `npm run generate:types` from docs/schemas. Do not edit by hand:\n" +
  " * change the schema (and the Python code it describes), then regenerate.\n" +
  " */";

/** `query-clients.v1` becomes `QueryClientsV1`, the name this file is exported under. */
function namespaceOf(stem) {
  return stem
    .split(/[^A-Za-z0-9]+/)
    .filter(Boolean)
    .map((part) => part[0].toUpperCase() + part.slice(1))
    .join("");
}

const files = (await Promise.all([schemaDir, terminalSchemaDir].map(async (directory) =>
  (await readdir(directory)).filter((name) => name.endsWith(".schema.json")).map((name) => ({ name, directory }))
))).flat().sort((a, b) => a.name.localeCompare(b.name, "en"));
if (files.length === 0) throw new Error(`no schemas found in ${schemaDir}`);

await rm(outDir, { recursive: true, force: true });
await mkdir(outDir, { recursive: true });

const exports = [];
for (const { name: file, directory } of files) {
  const stem = file.replace(/\.schema\.json$/, "");
  const schema = JSON.parse(await readFile(path.join(directory, file), "utf8"));
  const source = await compile(schema, stem, {
    bannerComment: directory === terminalSchemaDir ? banner.replace("docs/schemas", "docs/terminal") : banner,
    cwd: schemaDir,
    additionalProperties: true,
    format: true,
    style: { singleQuote: false, printWidth: 100 },
  });
  await writeFile(path.join(outDir, `${stem}.ts`), source);
  exports.push(`export type * as ${namespaceOf(stem)} from "./${stem}";`);
}

await writeFile(path.join(outDir, "index.ts"), `${banner}\n\n${exports.join("\n")}\n`);
console.log(`generated ${files.length} schema files in ${path.relative(root, outDir)}`);
